[package]
name = "rangerkit"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
rangerkit-core = { path = "../rangerkit-core" }
serde_json = "1.0.140"
