[package]
name = "rangerkit"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
crossterm = "0.29.0"
nu-ansi-term = "0.50.1"
rangerkit-core = { path = "../rangerkit-core" }
ratatui = "0.29.0"
serde_json = "1.0.140"
